### PR TITLE
delete previous bindings metadata

### LINKED ISSUE #27: error: custom attribute panicked
full stack trace:
```rs
error: custom attribute panicked
 --> src/lib.rs:3:1
  |
3 | #[deno_bindgen]
  | ^^^^^^^^^^^^^^^
  |
  = help: message: called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)
```

repro code:
```rs
#[deno_bindgen::deno_bindgen]
fn greet() -> i32 {
    return 42;
}
```

Fixed by deleting `bindings.json` in project root

### PR DESCRIPTION
**Pull request by grian32**
fixes #27

### CODE REVIEW

File: cli.ts [hunk 1]
```diff
@@ -44,6 +44,7 @@ async function generate() {
   await Deno.remove("bindings.json");
 }
 
+await Deno.remove("bindings.json");
```
Comment (littledivy) [inline cli.ts:47]: Put this in a try catch and ignore the NotFound error (happens on first run)

**Review by littledivy — CHANGES_REQUESTED** [review]

File: cli.ts (hunk 1 above)
Comment (grian32) [reply cli.ts]: just made the catch a no-op, hopefully shouldnt matter since its only there to fix an error

**Review by littledivy — APPROVED** [review]
